version: '3.9'

services:
  nginx:
    container_name: reverse_proxy
    image: nginx:alpine
    ports:
      - '8000:80'
    volumes:
      - ./php/:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - node

  php:
    container_name: php
    image: php:8.0-apache
    volumes:
      - ./php/:/var/www/html

  node:
    image: node:18.10-slim
    environment:
      - NODE_ENV=production
    working_dir: /app
    volumes:
      - ./node/:/app
    depends_on:
      - php
    command: >
      sh -c '
        if [ -z "$(which yarn)" ]; then
          echo "Yarn not found, installing...";
          npm install -g yarn;
        else
          echo "Yarn is already installed";
        fi &&
        if [ -z "$(which typescript)" ]; then
          echo "Typescript not found, installing...";
          npm install -g typescript;
        else
          echo "Typescript is already installed";
        fi &&
        yarn install &&
        npx prisma generate &&
        yarn start
      '
